### ISSUE TITLE
MAC Permission Denied

### ISSUE THREAD

**Issue by MarcoMedrano** [rjwojcicki/SimpleCompare#2]
Hi, thanks for the plugin, unfortunately, it is not working on mac. Next error is raised:
```
Traceback (most recent call last):
  File "fman/impl/plugins/command_registry.py", line 128, in _execute_command
  File "/Users/marcomedrano/Library/Application Support/fman/Plugins/Third-party/SimpleCompare/simpleCompare/__init__.py", line 25, in __call__
    ComparisonToolRunner.compare_files(savedToCompare, selectedFile)
  File "/Users/marcomedrano/Library/Application Support/fman/Plugins/Third-party/SimpleCompare/simpleCompare/__init__.py", line 48, in compare_files
    subprocess.call([comparisonTool, as_human_readable(lhsFile), as_human_readable(rhsFile)])
  File "subprocess.py", line 287, in call
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1364, in _execute_child
PermissionError: [Errno 13] Permission denied: '/Applications/Meld.app'
```
The same happens with Byond Comparer.

OS: Macos Mojave

**Comment by MKabX** [comment]
I ran into the same issue. It is caused by the way the comparison app gets launched which dies not work under Macos. I opened a Pull request that should fix the issue.
#3
